version: "3"

services: 
  sonarqube:
    image: sonarqube:8.9.0-community
    container_name: sonarqube
    environment: 
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    ports:
      - 9000:9000
    networks: 
      - atnet
    depends_on: 
      - postgres
    volumes:
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_data:/opt/sonarqube/data
    restart: always
  
  postgres:
    image: postgres:12.1-alpine
    container_name: postgresdb
    environment: 
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - postgresql:/var/lib/postgresql
    networks: 
      - atnet
    restart: always
  
networks:
  atnet:

volumes:
  postgresql_data:
  postgresql:
  sonarqube_logs:
  sonarqube_extensions:
  sonarqube_data: